# -*- coding: utf-8 -*-
"""Bard API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXRbWDYQ8n0lOumD1PwSbTyW4dLEjm5v
"""

!pip install bardapi>=0.1.8

# simple usage
import bardapi
from bardapi import Bard
import os

## set your __Secure-1PSID value to key
token='YOUR-SECURE-1PSID-HERE'
input_text = "Hello Bard!"

response = bardapi.core.Bard(token).get_answer(input_text)['content']

print(response)